"""Emits a crew directory from a validated `CrewConfig`.

Output layout:
    <out_root>/<crew-name>/
        README.md
        agents/
            <agent-id>.yaml
        tools/                  # only if the crew has custom tools
            <tool-id>.py
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from crewdefine.schema import AgentConfig, CrewConfig, ToolSpec
from crewdefine.yaml_format import dump_agent_yaml


@dataclass
class WriteResult:
    crew_dir: Path
    agent_files: list[Path]
    tool_files: list[Path]
    readme: Path


def write_crew(crew: CrewConfig, out_root: Path, *, overwrite: bool = False) -> WriteResult:
    """Write the full crew to disk. Caller must have already validated `crew`."""
    crew_dir = out_root / crew.name
    agents_dir = crew_dir / "agents"
    tools_dir = crew_dir / "tools"

    if crew_dir.exists() and not overwrite:
        raise FileExistsError(
            f"{crew_dir} already exists. Pass overwrite=True or pick a different crew name."
        )

    agents_dir.mkdir(parents=True, exist_ok=True)
    if crew.custom_tools:
        tools_dir.mkdir(parents=True, exist_ok=True)

    agent_files = [_write_agent(agent, agents_dir) for agent in crew.agents]
    tool_files = [_write_tool_stub(tool, tools_dir) for tool in crew.custom_tools]
    readme = _write_readme(crew, crew_dir)

    return WriteResult(
        crew_dir=crew_dir, agent_files=agent_files, tool_files=tool_files, readme=readme
    )


def write_single_agent(agent: AgentConfig, crew_dir: Path, *, overwrite: bool = False) -> Path:
    """Write or overwrite one agent YAML inside an existing crew directory."""
    agents_dir = crew_dir / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    target = agents_dir / f"{agent.id}.yaml"
    if target.exists() and not overwrite:
        raise FileExistsError(f"{target} already exists. Pass overwrite=True to replace.")
    target.write_text(dump_agent_yaml(agent.to_yaml_dict()), encoding="utf-8")
    return target


def _write_agent(agent: AgentConfig, agents_dir: Path) -> Path:
    target = agents_dir / f"{agent.id}.yaml"
    target.write_text(dump_agent_yaml(agent.to_yaml_dict()), encoding="utf-8")
    return target


def _write_tool_stub(tool: ToolSpec, tools_dir: Path) -> Path:
    target = tools_dir / f"{tool.id}.py"
    target.write_text(_render_tool_stub(tool), encoding="utf-8")
    return target


def _render_tool_stub(tool: ToolSpec) -> str:
    """Render a Python stub in LabZ's `TOOL_DEFINITIONS` format.

    The stub intentionally has TODOs rather than raising NotImplementedError
    so that imports don't blow up before a dev fills the body in.
    """
    properties_lines: list[str] = []
    required: list[str] = []
    for p in tool.parameters:
        properties_lines.append(
            f'        "{p.name}": {{"type": "{p.type}", "description": {p.description!r}}},'
        )
        if p.required:
            required.append(p.name)

    properties_block = "\n".join(properties_lines) if properties_lines else ""
    required_repr = repr(required)
    params_sig = ", ".join(p.name for p in tool.parameters)

    return f'''"""Stub for the `{tool.id}` tool.

Generated by CrewDefine. Implement `{tool.id}()` below, then register
`TOOL_DEFINITION` and the function in LabZ's `backend/src/agents/tools/__init__.py`.
"""

from __future__ import annotations

from typing import Any


TOOL_DEFINITION: dict[str, Any] = {{
    "type": "function",
    "function": {{
        "name": "{tool.id}",
        "description": {tool.description!r},
        "parameters": {{
            "type": "object",
            "properties": {{
{properties_block}
            }},
            "required": {required_repr},
        }},
    }},
}}


def {tool.id}({params_sig}) -> dict[str, Any]:  # noqa: D401
    """TODO: implement this tool. Returns a JSON-serializable result dict."""
    raise NotImplementedError("TODO: implement {tool.id}")
'''


def _write_readme(crew: CrewConfig, crew_dir: Path) -> Path:
    agent_rows = "\n".join(f"| `{a.id}` | {a.name} | {a.role} |" for a in crew.agents)
    tool_rows = (
        "\n".join(f"| `{t.id}` | {t.description} |" for t in crew.custom_tools)
        or "_None — this crew uses only built-in LabZ tools._"
    )

    delegation_lines = []
    for a in crew.agents:
        if a.can_delegate_to:
            targets = ", ".join(f"`{t}`" for t in a.can_delegate_to)
            delegation_lines.append(f"- `{a.id}` → {targets}")
    delegation_block = (
        "\n".join(delegation_lines) if delegation_lines else "_No delegation configured._"
    )

    content = f"""# {crew.name}

{crew.description}

## Agents

| ID | Name | Role |
| --- | --- | --- |
{agent_rows}

## Custom tools

| ID | Description |
| --- | --- |
{tool_rows}

## Delegation graph

{delegation_block}

## Installing into LabZ

1. Copy every file under `agents/` into `LabZ/backend/src/agents/config/`.
2. Copy every file under `tools/` into `LabZ/backend/src/agents/tools/` and register each `TOOL_DEFINITION` + function in `tools/__init__.py`.
3. Restart the LabZ backend. The registry will pick up the new agent YAMLs automatically.

Generated by [CrewDefine](https://github.com/davidinwald/CrewDefine).
"""
    target = crew_dir / "README.md"
    target.write_text(content, encoding="utf-8")
    return target
